package entity;
// Generated 25/05/2016 10:44:20 AM by Hibernate Tools 4.3.1



/**
 * Employeedetail generated by hbm2java
 */
public class Employeedetail  implements java.io.Serializable {


     private Integer employeeId;
     private Employee employee;
     private String street;
     private String city;
     private String state;
     private String country;

    public Employeedetail() {
    }

	
    public Employeedetail(Employee employee) {
        this.employee = employee;
    }
    
    public Employeedetail(Employee employee, String street, String city, String state, String country) {
       this.employee = employee;
       this.street = street;
       this.city = city;
       this.state = state;
       this.country = country;
    }
    
    public Employeedetail(String street, String city, String state, String country) {
        this.street = street;
        this.city = city;
        this.state = state;
        this.country = country;
    }
   
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


